[project]
name = 'apex-yield-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.apex-vault]
path = 'contracts/apex-vault.clar'
clarity_version = 2
epoch = '2.5'

[contracts.mock-usdcx]
path = 'contracts/mock-usdcx.clar'
clarity_version = 2
epoch = '2.5'

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 2
epoch = '2.5'

[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lint_groups]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
